@startuml Public Prosecution Service

hide empty members
hide empty methods

package investigation {
    class CriminalOffence {
    }

    class OffenceAdvice {
    }

    class PoliceInvestigationDetails {
    }

    class PreChargeDecisionCase {
        void RecordAlternativeOffenceAdvice(Suspect, OffenceAdvice)
        OffenceAdvice GetOffenceAdviceFor(Suspect)
    }

    class Suspect    {
    }
}

package preparation {
    class CriminalCase {
    }

    class Defendant {
    }

    class PoliceCaseFile {
    }
}

class PNCId {
}

class PublicProsecutionService {
    PreChargeDecisionCase ReceiveRequestForPreChargeDecisionCase(PoliceInvestigationDetails)
    CriminalCase AcceptCaseFile(PoliceCaseFile)
}

Suspect *-- "1" CriminalOffence

PoliceCaseFile *-- "1" PNCId

PoliceCaseFile *-- "*" Defendant

PoliceInvestigationDetails *-- "1" PNCId

PoliceInvestigationDetails *-- "*" Suspect

PreChargeDecisionCase *-- "*" Suspect

PreChargeDecisionCase *-- "*" OffenceAdvice

CriminalCase *-- "1" PNCId

CriminalCase *-- "*" Suspect

CriminalCase *-- "*" Defendant

PublicProsecutionService --> CriminalCase : <<creates>>

PublicProsecutionService --> PoliceInvestigationDetails : <<uses>>

@enduml
