@startuml
hide empty members
hide empty methods

class CriminalCase {
}

class CriminalOffence {
}

class PNCId {
}

class PoliceInvestigation {
}

class PreChargeDecision {
    void recordAlternativeOffenceAdvice(Suspect, OffenceAdvice)
    OffenceAdvice getOffenceAdviceFor(Suspect)
}

class AlternativeOffenceAdvice {
}

class Suspect    {
}

Suspect *-- "1" CriminalOffence

PoliceInvestigation *-- "*" Suspect

PoliceInvestigation *-- "1" PNCId

PreChargeDecision *-- "*" AlternativeOffenceAdvice
@enduml
